apiVersion: batch/v1
kind: CronJob
metadata:
  name: sftp-adapter-1
  namespace: default
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
            - name: sftp-adapter-container
              image: gcr.io/clus-demo/sftp-adapter-image-1
              imagePullPolicy: IfNotPresent
              command:
                - npm
                - run
                - start
              env:
                - name: CLIENT_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: CLIENT_EMAIL
                - name: CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: CLIENT_ID
                - name: PRIVATE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: PRIVATE_KEY
                - name: PROJECT_ID
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: PROJECT_ID
                - name: TOKEN_URL
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: TOKEN_URL
                - name: allFileExtension
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: allFileExtension
                - name: apiURL
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: apiURL
                - name: bucketName
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: bucketName
                - name: destinationPath
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: destinationPath
                - name: ftpServerPath
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: ftpServerPath
                - name: HOST
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: HOST
                - name: PORT
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: PORT
                - name: USER
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: USER
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: PASSWORD
                - name: SECURE
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: SECURE
                - name: API_PORT
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: API_PORT
                - name: API_ROOT
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: API_ROOT
                - name: API_VERSION
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: API_VERSION
                - name: API_HOST
                  valueFrom:
                    secretKeyRef:
                      name: sftp-service-secret
                      key: API_HOST
          restartPolicy: OnFailure
